### ISSUE TITLE
[master] ncf_pos: Múltiples problemas en el POS

### ISSUE THREAD

**Issue by gustavovalverde** [eneldoserrata/marcos_addons#37]
Cuando se activa el POS del restaurante se presentan múltiples inconvenientes si el módulo ncf_pos está activo:

1. En la Pantalla de las mesas sale un botón (adicional) de Cancelar que no hace nada.
2. Las órdenes no se imprimen, se quedan colgadas hasta que consumen los recursos del CPU
3. Las notas no aparecen en cada línea de la orden; es como si no se hayan escrito.

**Comment by eneldoserrata** [comment]
El ncf_pos quedo deprecate para la version 10 ahora solo se estara trabajando ncf_pos_premium
