### ISSUE TITLE
El modulo RNC Validation no aparece  por los comentarios en el archivo __manifest_.py

### ISSUE THREAD

**Issue by Franklinmarte** [eneldoserrata/marcos_addons#49]
El modulo RNC Validation no aparece en el repositorio de aplicaciones de odoo. cuando borre los comentarios que tiene arriba antes de los datos .json, aparecio inmediatamente

**Comment by eneldoserrata** [comment]
Ese modulo esta deprecate para la version 10

**Comment by eneldoserrata** [comment]
Ese modulo esta deprecate para la version 10
